program pSupport;

{$APPTYPE CONSOLE}

{$R *.res}


uses
  superobject in 'Core\External\superobject.pas',
  superxmlparser in 'Core\External\superxmlparser.pas',
  uThreads in 'Core\uThreads.pas',
  uBackOffice in 'Core\uBackOffice.pas',
  uThreadSafeClass in 'Core\SyncObjs\uThreadSafeClass.pas',
  uSyncObjs in 'Core\SyncObjs\uSyncObjs.pas',
  uThreadSafeManager in 'Core\SyncObjs\uThreadSafeManager.pas',
  uScheduler in 'Core\uScheduler.pas',
  uSocialClasses in 'Core\uSocialClasses.pas',
  uZipCompressor in 'Core\uZipCompressor.pas',
  ucommandprocessor in 'Core\ucommandprocessor.pas',
  uDBManager in 'Core\DB\uDBManager.pas',
  uclient in 'Core\uclient.pas',
  uhttpserver in 'Core\uhttpserver.pas',
  uConstants in 'Core\uConstants.pas',
  utcpserver in 'Core\utcpserver.pas',
  uMonitor in 'Core\uMonitor.pas',
  uLogicThreads in 'Core\uLogicThreads.pas',
  ulog in 'Core\ulog.pas',
  uConfig in 'Core\uConfig.pas',
  uInit in 'Core\uInit.pas',
  uIOclasses in 'Core\uIOclasses.pas',
  uQueue in 'Core\uQueue.pas',
  uModerators in 'Support\uModerators.pas',
  uModerator in 'Support\uModerator.pas',
  uExceptions in 'Core\uExceptions.pas',
  uGetHttpThread in 'Core\uGetHttpThread.pas',
  uConsole in 'Core\uConsole.pas',
  uConsoleCP in 'Core\uConsoleCP.pas',
  usessions in 'Core\usessions.pas',
  uSocketCommands in 'Support\uSocketCommands.pas',
  uDebugTimer in 'Core\Debug\uDebugTimer.pas',
  uClientLocalization in 'Core\Localization\uClientLocalization.pas',
  uSystemMessagesLocalization in 'Core\Localization\uSystemMessagesLocalization.pas',
  uCensor in 'Core\Funcs\uCensor.pas',
  uFiles in 'Core\Funcs\uFiles.pas',
  uFileUploader in 'Core\Funcs\uFileUploader.pas',
  umd5hash in 'Core\Funcs\umd5hash.pas',
  uHMAChash in 'Core\Funcs\uHMAChash.pas',
  uOpenSSLFuncs in 'Core\Funcs\uOpenSSLFuncs.pas',
  ureboot in 'Core\Funcs\ureboot.pas',
  uStrings in 'Core\Funcs\uStrings.pas',
  uUnixTime in 'Core\Funcs\uUnixTime.pas',
  uPlatforms in 'Core\Platforms\uPlatforms.pas',
  uPlatformSocEngine in 'Core\Platforms\uPlatformSocEngine.pas',
  uPlatformsManager in 'Core\Platforms\uPlatformsManager.pas',
  uTrackerLight in 'Core\uTrackerLight.pas',
  uHTTPSender in 'Core\uHTTPSender.pas',
  uDebug in 'Core\Debug\uDebug.pas',
  uObjectSize in 'Core\Debug\uObjectSize.pas',
  uPlatformVK in 'Core\Platforms\uPlatformVK.pas',
  uHTTPRequest in 'Core\uHTTPRequest.pas',
  uPlatformOK in 'Core\Platforms\uPlatformOK.pas',
  uPlatformMM in 'Core\Platforms\uPlatformMM.pas',
  uPlatformDevelopers in 'Core\Platforms\uPlatformDevelopers.pas',
  uPanformAppEngine in 'Core\Platforms\uPanformAppEngine.pas',
  uCachedObjects in 'Core\uCachedObjects.pas',
  uBackOfficeGA in 'Core\uBackOfficeGA.pas',
  uIniFiles in 'Core\uIniFiles.pas',
  uPlatformFB in 'Core\Platforms\uPlatformFB.pas',
  libeay32 in 'Core\External\libeay32.pas',
  uHTTPSRequest in 'Core\uHTTPSRequest.pas';

begin

end.
